#DATABASE CONFIGURATION
spring.datasource.url=jdbc:mariadb://localhost:3307/invoicemanagement
spring.datasource.username = root
spring.datasource.password = Scooter18
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update

#SQL OPTIMIZATION
spring.datasource.jpa.show-sql = true
spring.jpa.properties.hibernate.globally_quoted_identifiers = true
spring.jpa.properties.hibernate.dialect.format_sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB10Dialect
spring.sql.init.mode = never
spring.sql.init.continue-on-error = false
#SERVER CONFIG
sever.port = 8081