#DATABASE CONFIGURATION
spring.datasource.url=jdbc:mariadb://localhost:3307/invoicemanagement
spring.datasource.username = root
spring.datasource.password = Scooter18
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update

#SQL OPTIMIZATION
spring.datasource.jpa.show-sql = true
spring.jpa.properties.hibernate.globally_quoted_identifiers = true
spring.jpa.properties.hibernate.dialect.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.sql.init.mode = never
spring.sql.init.continue-on-error = false

#SERVER CONFIG
server.port = 8081

#DEBUGGING CONFIG
logging.level.org.springframework.security = DEBUG


#TWILIO CONFIG
twilio.carrier.sid.key = AC8098c5fae31cbb45b9fa9d80c8b26e18
twilio.carrier.from.number = +18669513570
twilio.carrier.token.key = c30045c86b6374c2c1d30475c391692c

#JWT CONFIG
jwt.secret = mysupercomplexsecret